/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Proyecto.Grafo_MatrizAdyacencia;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
/**
 *Esta clase crea la GUI para el programa de vuelos
 * @author Luis Toscano, Alejandro Gómez y Yeison Cáceres 
 */
public class VuelosGUI extends javax.swing.JFrame {
    
    private Grafo_MatrizAdyacencia grafoVuelos;
    final String[] mapCiudades;
    DefaultTableModel modelo;
    String str_novedades_lluvia = "";
    String[] novedades_ofertas = new String[30];
    int count_novedades_ofertas = -1;
    /**
     * Creates new form Mapa
     */
    public VuelosGUI() {
        initComponents();
        
        novedades_icon.setVisible(false);
        
        //Creando el grafo cuyas aristas representan los vuelos directos, el costo de vuelo y el tiempo de vuelo
        this.grafoVuelos = new Grafo_MatrizAdyacencia (10);
        grafoVuelos.agregarArista(0, 1, 50,30);
        grafoVuelos.agregarArista(0, 2, 80,45);
        grafoVuelos.agregarArista(0, 8, 75,45);
        grafoVuelos.agregarArista(0, 7, 100,40);
        
        grafoVuelos.agregarArista(1, 2, 60,35);
        grafoVuelos.agregarArista(1, 9, 60,30);
        grafoVuelos.agregarArista(1, 5, 90,25);
        
        grafoVuelos.agregarArista(2, 3, 80,30);
        grafoVuelos.agregarArista(2, 6, 100,80);
        
        grafoVuelos.agregarArista(3, 6, 120,90);
        grafoVuelos.agregarArista(3, 9, 90,50);
        
        grafoVuelos.agregarArista(4, 6, 100,50);
        grafoVuelos.agregarArista(4, 7, 130,35);
        
        grafoVuelos.agregarArista(5, 8, 180,75);
        
        grafoVuelos.agregarArista(7, 8, 120,60);
        
        //Creando el modelo de la tabla de vuelos
        modelo = new DefaultTableModel();
        modelo.addColumn("Origen");
        modelo.addColumn("Destino");
        modelo.addColumn("Costo ($)");
        modelo.addColumn("Tiempo (min)");
        this.tabla.setModel(modelo);
        
        
        //Mapeo de las 10 principales ciudades de Colombia para no mostrar números sino ciudades
        mapCiudades = new String[] {
        "Bucaramanga",
        "Bogotá",
        "Medellín",
        "Cali",
        "Barranquilla",
        "Armenia",
        "San Andrés",
        "Valledupar",
        "Arauca",
        "Ibagué"
        };
        
        updateTabla(); //Activando la tabla
        setExtendedState(this.MAXIMIZED_BOTH); //Pantalla maximixada
    }

    /**
     * METODO GENERADO POR NET BEANS PARA CREAR LA GUI
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        PanelPrincipal = new javax.swing.JPanel();
        mapa_panel = new javax.swing.JPanel();
        mapa_img = new javax.swing.JLabel();
        mapa_title_tlb = new javax.swing.JLabel();
        sistema_panel = new javax.swing.JPanel();
        panel_eventos = new javax.swing.JTabbedPane();
        catastrofe_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        texto_catastrofe = new javax.swing.JTextArea();
        catastrofe_btn = new javax.swing.JButton();
        restore_catastrofe_btn = new javax.swing.JButton();
        ciudades_catastrofe_cb = new javax.swing.JComboBox<>();
        ciudades_catastrofe_lbl = new javax.swing.JLabel();
        salida_catastrofe = new javax.swing.JLabel();
        subsalida_catastrofe = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tour_descripcion = new javax.swing.JTextArea();
        tour_precio_btn = new javax.swing.JButton();
        tour_tiempo_btn = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tour_salida_camino = new javax.swing.JTextArea();
        tour_precio_lbl = new javax.swing.JLabel();
        tour_tiempo_lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lluvia_txt = new javax.swing.JTextArea();
        lluvia_detener_btn = new javax.swing.JButton();
        lluvia_aplicar_btn = new javax.swing.JButton();
        oferta_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        oferta_texto = new javax.swing.JTextArea();
        oferta_cb_1 = new javax.swing.JComboBox<>();
        oferta_cb_2 = new javax.swing.JComboBox<>();
        oferta_vuelo_icon = new javax.swing.JLabel();
        oferta_aplicar_btn = new javax.swing.JButton();
        oferta_eliminar_btn = new javax.swing.JButton();
        oferta_porcentaje_lbl = new javax.swing.JLabel();
        oferta_porcentaje_num = new javax.swing.JSpinner();
        oferta_porciento_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        novedades_icon = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        novedades_txt_area = new javax.swing.JTextArea();
        novedades_title = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        novedades_txt_area_2 = new javax.swing.JTextArea();
        vuelo_especifico_res = new javax.swing.JPanel();
        vuelo_esp_title = new javax.swing.JLabel();
        vuelo_esp_cb2 = new javax.swing.JComboBox<>();
        vuelo_esp_cb1 = new javax.swing.JComboBox<>();
        vuelo_esp_desde_lbl = new javax.swing.JLabel();
        vuelo_esp_hasta_lbl = new javax.swing.JLabel();
        vuelo_esp_precio_btn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        vuelo_esp_salida_txt = new javax.swing.JTextArea();
        vuelo_esp_tiempo_btn = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));

        PanelPrincipal.setBackground(new java.awt.Color(204, 204, 255));

        mapa_panel.setBackground(new java.awt.Color(255, 255, 153));
        mapa_panel.setToolTipText("");

        mapa_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/mapa-colobia.jpg"))); // NOI18N

        mapa_title_tlb.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        mapa_title_tlb.setText("Mapa de la República");

        sistema_panel.setBackground(new java.awt.Color(153, 153, 255));

        panel_eventos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        texto_catastrofe.setEditable(false);
        texto_catastrofe.setColumns(20);
        texto_catastrofe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        texto_catastrofe.setLineWrap(true);
        texto_catastrofe.setRows(5);
        texto_catastrofe.setText("Este botón activa un método que simula un caso del\nlluvia extrema que trae como consecuencia que los \nprecios de los vuelos aumenten");
        texto_catastrofe.setMargin(new java.awt.Insets(1, 6, 2, 1));
        jScrollPane3.setViewportView(texto_catastrofe);

        catastrofe_btn.setText("Provocar una catástrofe");
        catastrofe_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catastrofe_btnActionPerformed(evt);
            }
        });

        restore_catastrofe_btn.setText("Restaurar");
        restore_catastrofe_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restore_catastrofe_btnActionPerformed(evt);
            }
        });

        ciudades_catastrofe_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bucaramanga", "Bogotá", "Medellín", "Cali", "Barranquilla", "Armenia", "San Andrés", "Valledupar", "Arauca", "Ibagué" }));

        ciudades_catastrofe_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ciudades_catastrofe_lbl.setText("Ciudad:");

        subsalida_catastrofe.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout catastrofe_panelLayout = new javax.swing.GroupLayout(catastrofe_panel);
        catastrofe_panel.setLayout(catastrofe_panelLayout);
        catastrofe_panelLayout.setHorizontalGroup(
            catastrofe_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catastrofe_panelLayout.createSequentialGroup()
                .addGroup(catastrofe_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(catastrofe_panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(catastrofe_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subsalida_catastrofe)
                            .addComponent(salida_catastrofe, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(catastrofe_panelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(catastrofe_panelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(ciudades_catastrofe_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(ciudades_catastrofe_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(catastrofe_panelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(catastrofe_btn)
                        .addGap(18, 18, 18)
                        .addComponent(restore_catastrofe_btn)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        catastrofe_panelLayout.setVerticalGroup(
            catastrofe_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catastrofe_panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(catastrofe_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudades_catastrofe_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ciudades_catastrofe_lbl))
                .addGap(18, 18, 18)
                .addGroup(catastrofe_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catastrofe_btn)
                    .addComponent(restore_catastrofe_btn))
                .addGap(18, 18, 18)
                .addComponent(salida_catastrofe, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subsalida_catastrofe)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        catastrofe_btn.getAccessibleContext().setAccessibleName("catastrofe_btn");
        ciudades_catastrofe_lbl.getAccessibleContext().setAccessibleDescription("");
        ciudades_catastrofe_lbl.getAccessibleContext().setAccessibleParent(ciudades_catastrofe_cb);

        panel_eventos.addTab("Catástrofe", new javax.swing.ImageIcon(getClass().getResource("/Vista/terremoto.png")), catastrofe_panel); // NOI18N
        catastrofe_panel.getAccessibleContext().setAccessibleName("catastrofe_panel");

        tour_descripcion.setEditable(false);
        tour_descripcion.setColumns(20);
        tour_descripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tour_descripcion.setLineWrap(true);
        tour_descripcion.setRows(5);
        tour_descripcion.setText("Obtener un tour con el que se recorren todos los posibles destinos al menor precio posible, o en el menor tiempo posible. El usuario decide");
        tour_descripcion.setAutoscrolls(false);
        jScrollPane4.setViewportView(tour_descripcion);

        tour_precio_btn.setText("Tour precio");
        tour_precio_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour_precio_btnActionPerformed(evt);
            }
        });

        tour_tiempo_btn.setText("Tour tiempo");
        tour_tiempo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tour_tiempo_btnActionPerformed(evt);
            }
        });

        tour_salida_camino.setEditable(false);
        tour_salida_camino.setColumns(20);
        tour_salida_camino.setLineWrap(true);
        tour_salida_camino.setRows(5);
        jScrollPane7.setViewportView(tour_salida_camino);

        tour_precio_lbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N

        tour_tiempo_lbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(tour_precio_btn)
                        .addGap(18, 18, 18)
                        .addComponent(tour_tiempo_btn))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tour_precio_lbl)
                        .addGap(35, 35, 35)
                        .addComponent(tour_tiempo_lbl)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tour_precio_btn)
                    .addComponent(tour_tiempo_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tour_precio_lbl)
                    .addComponent(tour_tiempo_lbl))
                .addContainerGap())
        );

        panel_eventos.addTab("Tour", new javax.swing.ImageIcon(getClass().getResource("/Vista/tour.png")), jPanel4); // NOI18N

        lluvia_txt.setEditable(false);
        lluvia_txt.setColumns(20);
        lluvia_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lluvia_txt.setLineWrap(true);
        lluvia_txt.setRows(5);
        lluvia_txt.setText("Este botón activa un método que simula un caso de\nlluvia extrema que trae como consecuencia que los \nprecios de los vuelos aumenten");
        lluvia_txt.setMargin(new java.awt.Insets(1, 6, 2, 1));
        jScrollPane1.setViewportView(lluvia_txt);

        lluvia_detener_btn.setText("Detener lluvia");
        lluvia_detener_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lluvia_detener_btnActionPerformed(evt);
            }
        });

        lluvia_aplicar_btn.setText("Hacer que llueva");
        lluvia_aplicar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lluvia_aplicar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lluvia_aplicar_btn)
                        .addGap(18, 18, 18)
                        .addComponent(lluvia_detener_btn)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lluvia_detener_btn)
                    .addComponent(lluvia_aplicar_btn))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        panel_eventos.addTab("Lluvia", new javax.swing.ImageIcon(getClass().getResource("/Vista/gota-de-agua.png")), jPanel1); // NOI18N
        jPanel1.getAccessibleContext().setAccessibleName("lluvia_panel");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        oferta_texto.setEditable(false);
        oferta_texto.setColumns(20);
        oferta_texto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        oferta_texto.setRows(5);
        oferta_texto.setText("Puedes hacer una oferta para un vuelo de una ubi-\ncación específica a otra por medio de esta ventana.\nLo que hace es reducir el peso de la arista que re- \npresenta ese vuelo\n");
        oferta_texto.setAutoscrolls(false);
        jScrollPane2.setViewportView(oferta_texto);

        oferta_cb_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bucaramanga", "Bogotá", "Medellín", "Cali", "Barranquilla", "Armenia", "San Andrés", "Valledupar", "Arauca", "Ibagué" }));
        oferta_cb_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oferta_cb_1ActionPerformed(evt);
            }
        });

        oferta_vuelo_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/avion-negro.png"))); // NOI18N

        oferta_aplicar_btn.setText("Aplicar");
        oferta_aplicar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oferta_aplicar_btnActionPerformed(evt);
            }
        });

        oferta_eliminar_btn.setText("Eliminar");
        oferta_eliminar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oferta_eliminar_btnActionPerformed(evt);
            }
        });

        oferta_porcentaje_lbl.setText("Porcentaje de la oferta:");

        oferta_porcentaje_num.setModel(new javax.swing.SpinnerNumberModel(5, 5, 100, 5));

        oferta_porciento_lbl.setText("%");

        javax.swing.GroupLayout oferta_panelLayout = new javax.swing.GroupLayout(oferta_panel);
        oferta_panel.setLayout(oferta_panelLayout);
        oferta_panelLayout.setHorizontalGroup(
            oferta_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oferta_panelLayout.createSequentialGroup()
                .addGroup(oferta_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oferta_panelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(oferta_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(oferta_cb_1, 0, 164, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(oferta_vuelo_icon)
                        .addGap(18, 18, 18)
                        .addComponent(oferta_cb_2, 0, 164, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(oferta_panelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(oferta_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(oferta_panelLayout.createSequentialGroup()
                        .addComponent(oferta_aplicar_btn)
                        .addGap(18, 18, 18)
                        .addComponent(oferta_eliminar_btn))
                    .addGroup(oferta_panelLayout.createSequentialGroup()
                        .addComponent(oferta_porcentaje_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oferta_porcentaje_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oferta_porciento_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        oferta_panelLayout.setVerticalGroup(
            oferta_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oferta_panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(oferta_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oferta_vuelo_icon)
                    .addComponent(oferta_cb_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oferta_cb_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(oferta_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oferta_porcentaje_lbl)
                    .addComponent(oferta_porcentaje_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oferta_porciento_lbl))
                .addGap(18, 18, 18)
                .addGroup(oferta_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oferta_eliminar_btn)
                    .addComponent(oferta_aplicar_btn))
                .addGap(30, 30, 30))
        );

        panel_eventos.addTab("Oferta", new javax.swing.ImageIcon(getClass().getResource("/Vista/descuento.png")), oferta_panel); // NOI18N
        oferta_panel.getAccessibleContext().setAccessibleName("Oferta");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel2.setText("Sistema de vuelos comerciales");

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel5.setText("Todos los vuelos");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setEnabled(false);
        jScrollPane6.setViewportView(tabla);

        novedades_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/info-32.png"))); // NOI18N

        novedades_txt_area.setEditable(false);
        novedades_txt_area.setColumns(20);
        novedades_txt_area.setRows(5);
        novedades_txt_area.setAutoscrolls(false);
        novedades_txt_area.setBorder(null);
        jScrollPane5.setViewportView(novedades_txt_area);

        novedades_title.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        novedades_title.setText("Novedades");

        novedades_txt_area_2.setEditable(false);
        novedades_txt_area_2.setColumns(20);
        novedades_txt_area_2.setLineWrap(true);
        novedades_txt_area_2.setRows(5);
        jScrollPane9.setViewportView(novedades_txt_area_2);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 154, Short.MAX_VALUE)
                        .addComponent(novedades_title)
                        .addGap(167, 167, 167))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(novedades_icon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(novedades_title)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(novedades_icon)
                        .addGap(111, 111, 111))))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        vuelo_esp_title.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        vuelo_esp_title.setText("Vuelo específico");

        vuelo_esp_cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bucaramanga", "Bogotá", "Medellín", "Cali", "Barranquilla", "Armenia", "San Andrés", "Valledupar", "Arauca", "Ibagué" }));

        vuelo_esp_cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bucaramanga", "Bogotá", "Medellín", "Cali", "Barranquilla", "Armenia", "San Andrés", "Valledupar", "Arauca", "Ibagué" }));

        vuelo_esp_desde_lbl.setText("Desde");

        vuelo_esp_hasta_lbl.setText("Hasta");

        vuelo_esp_precio_btn.setText("Menor precio");
        vuelo_esp_precio_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vuelo_esp_precio_btnActionPerformed(evt);
            }
        });

        jLabel9.setText(".");

        vuelo_esp_salida_txt.setColumns(20);
        vuelo_esp_salida_txt.setLineWrap(true);
        vuelo_esp_salida_txt.setRows(5);
        jScrollPane8.setViewportView(vuelo_esp_salida_txt);

        vuelo_esp_tiempo_btn.setText("Menor tiempo");
        vuelo_esp_tiempo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vuelo_esp_tiempo_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vuelo_especifico_resLayout = new javax.swing.GroupLayout(vuelo_especifico_res);
        vuelo_especifico_res.setLayout(vuelo_especifico_resLayout);
        vuelo_especifico_resLayout.setHorizontalGroup(
            vuelo_especifico_resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vuelo_especifico_resLayout.createSequentialGroup()
                .addGroup(vuelo_especifico_resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, vuelo_especifico_resLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(vuelo_esp_desde_lbl)
                        .addGap(107, 107, 107)
                        .addComponent(vuelo_esp_hasta_lbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(vuelo_especifico_resLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(vuelo_esp_cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vuelo_esp_cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91))
            .addGroup(vuelo_especifico_resLayout.createSequentialGroup()
                .addGroup(vuelo_especifico_resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vuelo_especifico_resLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(vuelo_especifico_resLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(vuelo_esp_title))
                    .addGroup(vuelo_especifico_resLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(vuelo_esp_precio_btn)
                        .addGap(18, 18, 18)
                        .addComponent(vuelo_esp_tiempo_btn)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        vuelo_especifico_resLayout.setVerticalGroup(
            vuelo_especifico_resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vuelo_especifico_resLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(vuelo_esp_title)
                .addGap(18, 18, 18)
                .addGroup(vuelo_especifico_resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vuelo_esp_cb1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vuelo_esp_cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vuelo_especifico_resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vuelo_esp_desde_lbl)
                    .addComponent(vuelo_esp_hasta_lbl))
                .addGroup(vuelo_especifico_resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vuelo_especifico_resLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(vuelo_especifico_resLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(vuelo_especifico_resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vuelo_esp_precio_btn)
                            .addComponent(vuelo_esp_tiempo_btn))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout sistema_panelLayout = new javax.swing.GroupLayout(sistema_panel);
        sistema_panel.setLayout(sistema_panelLayout);
        sistema_panelLayout.setHorizontalGroup(
            sistema_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sistema_panelLayout.createSequentialGroup()
                .addGroup(sistema_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sistema_panelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE))
                    .addGroup(sistema_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(sistema_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vuelo_especifico_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sistema_panelLayout.setVerticalGroup(
            sistema_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sistema_panelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vuelo_especifico_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_eventos.getAccessibleContext().setAccessibleName("tab_panel");
        jLabel2.getAccessibleContext().setAccessibleName("sistema_title");

        javax.swing.GroupLayout mapa_panelLayout = new javax.swing.GroupLayout(mapa_panel);
        mapa_panel.setLayout(mapa_panelLayout);
        mapa_panelLayout.setHorizontalGroup(
            mapa_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapa_panelLayout.createSequentialGroup()
                .addGroup(mapa_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapa_panelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(mapa_img))
                    .addGroup(mapa_panelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(mapa_title_tlb)))
                .addGap(18, 18, 18)
                .addComponent(sistema_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mapa_panelLayout.setVerticalGroup(
            mapa_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapa_panelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(mapa_title_tlb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mapa_img)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapa_panelLayout.createSequentialGroup()
                .addComponent(sistema_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mapa_img.getAccessibleContext().setAccessibleName("mapa");
        mapa_title_tlb.getAccessibleContext().setAccessibleName("mapa_title");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(mapa_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(mapa_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Crea una catástrofe en una ciudad específica escogida
     * @param evt
     */
    private void catastrofe_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catastrofe_btnActionPerformed
 
        int idx = ciudades_catastrofe_cb.getSelectedIndex();
        grafoVuelos.metodoCatastrofe(idx);
        salida_catastrofe.setText("Ha ocurrido una catástrofe en: " + mapCiudades[idx] + ",");
        subsalida_catastrofe.setText("los vuelos a ese destino han sido cancelados");
        updateTabla();
    }//GEN-LAST:event_catastrofe_btnActionPerformed

    /**
     * Elimina una catástrofe en una ciudad específica
     * @param evt 
     */
    private void restore_catastrofe_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restore_catastrofe_btnActionPerformed

        int idx = ciudades_catastrofe_cb.getSelectedIndex();
        grafoVuelos.anularCatastrofe(idx);
        salida_catastrofe.setText("Se ha resuelto la catástrofe en: " + mapCiudades[idx] + ",");
        subsalida_catastrofe.setText("los vuelos a ese destino han sido restaurados");
        updateTabla();
    }//GEN-LAST:event_restore_catastrofe_btnActionPerformed

    /**
     * Crea una oferta de vuelo para el usuario (abarata el peso de la arista de ese vuelo, por lo que la oferta debe hacerse sobre un vuelo directo
     * @param evt
     */
    private void oferta_aplicar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oferta_aplicar_btnActionPerformed
        count_novedades_ofertas++;
        int idx1 = oferta_cb_1.getSelectedIndex();
        int idx2 = 0;
        
        //Calculando cual es la otra ciudad del descuento. Debido a la resticción de opciones del segundo combo box
        String ciudad2 = (String) oferta_cb_2.getSelectedItem();
        for (int i = 0; i < mapCiudades.length; i++) {
            if(mapCiudades[i].equals(ciudad2)){
                 idx2 = i;
            }
        }
        
        //Calculando el descuento
        float porcentajeNum = (int) oferta_porcentaje_num.getValue();
        float precioRegular = grafoVuelos.getMatrizPesos()[idx1][idx2];
        float descuento = (porcentajeNum/100)*precioRegular;
        float precioDescuento = precioRegular - descuento;
        
        grafoVuelos.metodoOfertas(idx1, idx2, precioDescuento);
        updateTabla(); //Actualiza la tabla
        
        //Actializa la vista de novedades
        novedades_icon.setVisible(true);
         novedades_ofertas[count_novedades_ofertas] =  "Descuento en los vuelos " + mapCiudades[idx1] + "-" + mapCiudades[idx2] + " del "  + (int)porcentajeNum + "%\n";
         String str ="";
        for (String novedades_oferta : novedades_ofertas) {
                if( novedades_oferta != null){
                str += novedades_oferta;
                }
            }          
          novedades_txt_area.setText(str);
    }//GEN-LAST:event_oferta_aplicar_btnActionPerformed

    /**
     * Elimina una oferta específica y elimina esa oferta del panel de novedades
     * @param evt 
     */
    private void oferta_eliminar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oferta_eliminar_btnActionPerformed
        int idx1 = oferta_cb_1.getSelectedIndex();
        int idx2 = 0;
        
        //Calculando cual es la otra ciudad del descuento
        String ciudad2 = (String) oferta_cb_2.getSelectedItem();
        for (int i = 0; i < mapCiudades.length; i++) {
            if(mapCiudades[i].equals(ciudad2)){
                 idx2 = i;
            }
        }
        
        grafoVuelos.anularOferta(idx1, idx2); //Anula la oferta
        updateTabla(); //Actualiza la tabla
        
        //Quitando la oferta del text area de novedades
        String str ="";
        for (int i = 0; i < novedades_ofertas.length; i++) {
            if( novedades_ofertas[i] != null){
                if( novedades_ofertas[i].contains(mapCiudades[idx1]) && novedades_ofertas[i].contains(mapCiudades[idx2])){
                 novedades_ofertas [i] = null;
                }
            }
        }        
        for (String novedades_oferta : novedades_ofertas) {
            if( novedades_oferta != null){
            str += novedades_oferta;
            }
        }        
       novedades_txt_area.setText(str);
    }//GEN-LAST:event_oferta_eliminar_btnActionPerformed

    /**
     * Modifica el segundo combo box del panel de ofertas para que solo puedan haber ofertas de vuelos directos
     * @param evt
     */
    private void oferta_cb_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oferta_cb_1ActionPerformed
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        int cb1 = oferta_cb_1.getSelectedIndex();
        for (int i = 0; i < grafoVuelos.getV(); i++) {
                if(grafoVuelos.getMatrizAdyacencia()[cb1][i] == 1){
                    modelo.addElement(mapCiudades[i]);
                } 
            }
        oferta_cb_2.setModel(modelo);
    }//GEN-LAST:event_oferta_cb_1ActionPerformed

    /**
     * Genera lluvias aleatoriamente, inhabilitando ciertos vértices. Probabilidad de 2%
     * @param evt 
     */
    private void lluvia_aplicar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lluvia_aplicar_btnActionPerformed
       String str_novedades_lluvias = grafoVuelos.metodoLluvia(str_novedades_lluvia, mapCiudades);
        novedades_txt_area_2.setText(str_novedades_lluvias);
        novedades_icon.setVisible(true);
        updateTabla();
    }//GEN-LAST:event_lluvia_aplicar_btnActionPerformed

    /**
     * Regresa el grafo a la normalidad deteniendo la lluvia
     * @param evt 
     */
    private void lluvia_detener_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lluvia_detener_btnActionPerformed
        grafoVuelos.restaurarPesos();
        novedades_txt_area_2.setText(str_novedades_lluvia);
        novedades_icon.setVisible(true);
        updateTabla();
    }//GEN-LAST:event_lluvia_detener_btnActionPerformed

    /**
     * Usa el método del árbol recubridor mínimo para poder hacer un tour donde se vaya a todas las ciudades por el menor precio posible.
     * Al ser un árbol recubridor mínimo, los vuelos pueden no tener sentido alguno
     * @param evt 
     */
    private void tour_precio_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour_precio_btnActionPerformed
       String [] salida =  grafoVuelos.metodoPrim(grafoVuelos.getMatrizPesos(), mapCiudades, false);
       tour_salida_camino.setText(salida[0]);
       tour_precio_lbl.setText(salida[1]);
       tour_tiempo_lbl.setText(salida[2]);
    }//GEN-LAST:event_tour_precio_btnActionPerformed

    /**
     * Usa el método del árbol recubridor mínimo para poder hacer un tour donde se vaya a todas las ciudades en el menor tiempo posible.
     * Al ser un árbol recubridor mínimo, los vuelos pueden no tener sentido alguno
     */
    private void tour_tiempo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tour_tiempo_btnActionPerformed
    String [] salida =  grafoVuelos.metodoPrim(grafoVuelos.getMatrizTiempo(), mapCiudades, true);
       tour_salida_camino.setText(salida[0]);
       tour_precio_lbl.setText(salida[1]);
       tour_tiempo_lbl.setText(salida[2]);
    }//GEN-LAST:event_tour_tiempo_btnActionPerformed

    /**
     * Calcula según el precio mínimo el camino más corto de un vuelo específico entre dos ciudades, ya sea directo o no (escalas).
     * @param evt 
     */
    private void vuelo_esp_precio_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vuelo_esp_precio_btnActionPerformed
        int idx1 = vuelo_esp_cb1.getSelectedIndex();
        int idx2 = vuelo_esp_cb2.getSelectedIndex();
        String salida = "La ruta de vuelos más barata desde " + mapCiudades[idx1] + " a " + mapCiudades[idx2] + " es: \n";
        if(idx1 == idx2){
            vuelo_esp_salida_txt.setText("Seleccione un vuelo válido");
        }
        else{
            salida += grafoVuelos.dijkstra(grafoVuelos.getMatrizPesos(),idx1, mapCiudades, idx2 ) + "$";
            vuelo_esp_salida_txt.setText(salida);
        }
    }//GEN-LAST:event_vuelo_esp_precio_btnActionPerformed

    /**
     * Calcula según el tiempo mínimo el camino más corto de un vuelo específico entre dos ciudades, ya sea directo o no (escalas).
     * @param evt 
     */
    private void vuelo_esp_tiempo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vuelo_esp_tiempo_btnActionPerformed
        int idx1 = vuelo_esp_cb1.getSelectedIndex();
        int idx2 = vuelo_esp_cb2.getSelectedIndex();
        String salida = "La ruta de vuelos más rápida desde " + mapCiudades[idx1] + " a " + mapCiudades[idx2] + " es: \n";
        if(idx1 == idx2){
            vuelo_esp_salida_txt.setText("No seleccione la misma ciudad");
        }
        else{
            salida += grafoVuelos.dijkstra(grafoVuelos.getMatrizTiempo(),idx1, mapCiudades, idx2) + " min";
            vuelo_esp_salida_txt.setText(salida);
        }
    }//GEN-LAST:event_vuelo_esp_tiempo_btnActionPerformed

    /**
     * Limpia y actualiza la tabla de vuelos
     */
    private void updateTabla(){
         //Limpiar tabla
       int rowCount = modelo.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        
        // Rellenar tabla de vuelos:
        int matrizAdy[][] = grafoVuelos.getMatrizAdyacencia();
        float matrizPesos[][]=grafoVuelos.getMatrizPesos();
        float matrizTiempo[][] = grafoVuelos.getMatrizTiempo();
        String [] infoVuelos = new String [4];
        for (int i = 0; i < grafoVuelos.getV(); i++) {
            for (int j = 0; j < grafoVuelos.getV(); j++) {
                if(matrizAdy[i][j] == 1 && matrizPesos[i][j] < 999)
                {
                    infoVuelos[0] = mapCiudades[i];
                    infoVuelos[1] = mapCiudades[j];
                    infoVuelos[2] = String.valueOf(matrizPesos[i][j]);
                    infoVuelos[3] = String.valueOf(matrizTiempo[i][j]);
                    modelo.addRow(infoVuelos);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton catastrofe_btn;
    private javax.swing.JPanel catastrofe_panel;
    private javax.swing.JComboBox<String> ciudades_catastrofe_cb;
    private javax.swing.JLabel ciudades_catastrofe_lbl;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton lluvia_aplicar_btn;
    private javax.swing.JButton lluvia_detener_btn;
    private javax.swing.JTextArea lluvia_txt;
    private javax.swing.JLabel mapa_img;
    private javax.swing.JPanel mapa_panel;
    private javax.swing.JLabel mapa_title_tlb;
    private javax.swing.JLabel novedades_icon;
    private javax.swing.JLabel novedades_title;
    private javax.swing.JTextArea novedades_txt_area;
    private javax.swing.JTextArea novedades_txt_area_2;
    private javax.swing.JButton oferta_aplicar_btn;
    private javax.swing.JComboBox<String> oferta_cb_1;
    private javax.swing.JComboBox<String> oferta_cb_2;
    private javax.swing.JButton oferta_eliminar_btn;
    private javax.swing.JPanel oferta_panel;
    private javax.swing.JLabel oferta_porcentaje_lbl;
    private javax.swing.JSpinner oferta_porcentaje_num;
    private javax.swing.JLabel oferta_porciento_lbl;
    private javax.swing.JTextArea oferta_texto;
    private javax.swing.JLabel oferta_vuelo_icon;
    private javax.swing.JTabbedPane panel_eventos;
    private javax.swing.JButton restore_catastrofe_btn;
    private javax.swing.JLabel salida_catastrofe;
    private javax.swing.JPanel sistema_panel;
    private javax.swing.JLabel subsalida_catastrofe;
    private javax.swing.JTable tabla;
    private javax.swing.JTextArea texto_catastrofe;
    private javax.swing.JTextArea tour_descripcion;
    private javax.swing.JButton tour_precio_btn;
    private javax.swing.JLabel tour_precio_lbl;
    private javax.swing.JTextArea tour_salida_camino;
    private javax.swing.JButton tour_tiempo_btn;
    private javax.swing.JLabel tour_tiempo_lbl;
    private javax.swing.JComboBox<String> vuelo_esp_cb1;
    private javax.swing.JComboBox<String> vuelo_esp_cb2;
    private javax.swing.JLabel vuelo_esp_desde_lbl;
    private javax.swing.JLabel vuelo_esp_hasta_lbl;
    private javax.swing.JButton vuelo_esp_precio_btn;
    private javax.swing.JTextArea vuelo_esp_salida_txt;
    private javax.swing.JButton vuelo_esp_tiempo_btn;
    private javax.swing.JLabel vuelo_esp_title;
    public javax.swing.JPanel vuelo_especifico_res;
    // End of variables declaration//GEN-END:variables
}
